on: [push, pull_request]
name: RUST Continuous integration

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Deps
      run: DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends liblzma-dev
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Format
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy -- --no-deps -Dwarnings
