on: [push, pull_request]
name: RUST Continuous integration

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Format
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy -- --no-deps -Dwarnings
